spring:
  application:
    name: fxz-server-system
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:fxz-application-common.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-circular-references: true

fxz:
  common:
    doc:
      author: "fxz"
      version: "0.0.1"
      title: "Art开发文档"
      description: "系统管理模块"
      basePackages:
        "[系统管理API]": com.fxz.system