server:
  port: 8202

spring:
  application:
    name: fxz-server-system-test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  boot:
    admin:
      client:
        url: http://${fxz-monitor-admin}:8401
        username: fxz
        password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8001
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: ${rabbitmq.url}
    port: 5672
    username: fxz
    password: 123456

  datasource:
    dynamic:
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FxzHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: 127255
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8


security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://${fxz-gateway}:8301/auth/user

  feign:
    hystrix:
      enabled: true
  hystrix:
    shareSecurityContext: true

  info:
    app:
      name: ${spring.application.name}
      description: "@project.description@"
      version: "@project.version@"

  management:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: ALWAYS