spring:
  application:
    name: fxz-generate
  cloud:
    nacos:
      config:
        server-addr: ${nacos.url}:8848
      discovery:
        server-addr: ${nacos.url}:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
nacos:
  url: 127.0.0.1