spring:
  application:
    name: art-auth
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      username: nacos
      password: art-nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:art-common.yaml

logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: debug

gitee:
  list:
    - appid: ${gitee_appid:94026f6491b102051726e28c718ab4706bb3a681939aee222119ef987a7170bf}
      # 码云 Gitee 秘钥
      secret: ${gitee_secret:7426207a5682480a71787d2356000b07e10a517fd972239c1e8d7afd9e3514ef}
      # 码云 Gitee 授权重定向地址的前缀，后面会自动拼接 码云 Gitee appid
      # 重定向地址前缀，没用appid。在码云Gitee配置完整重定向地址时，要与 redirect-uri-prefix + "/" + appid 相同
      redirect-uri-prefix: http://art-gateway:9999/auth/gitee/code
      client-id: fxz
      client-secret: 123456
      scope: gitee
      success-redirect-url: http://127.0.0.1:8000
      token-url: http://art-gateway:9999/auth

