spring:
  application:
    name: fxz-server-system
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
      username: nacos
      password: nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:fxz-application-common.yaml
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件上传大小
      max-request-size: 100MB # 总文件上传大小
  main:
    allow-circular-references: true