version: '3'
services:
  art-nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: art-nacos
    restart: unless-stopped                                              # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./nacos/logs:/home/nacos/logs"
    environment: # 设置环境变量,相当于docker run命令中的-e
      - PREFER_HOST_MODE=hostname                 # 如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      - MODE=standalone                           # 单机模式启动
      - SPRING_DATASOURCE_PLATFORM=mysql          # 数据源平台 仅支持mysql或不保存empty
      # TODO 修改mysql连接信息
      - MYSQL_SERVICE_HOST=172.16.16.88           # 注：这里不能为`127.0.0.1`或`localhost`方式！！！
      - MYSQL_SERVICE_DB_NAME=art_nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=art-mysql-password
      # TODO 修改JVM调优参数
      - JVM_XMS=128m   #-Xms default :2g
      - JVM_XMX=128m   #-Xmx default :2g
      - JVM_XMN=64m    #-Xmn default :1g
      - JVM_MS=32m     #-XX:MetaspaceSize default :128m
      - JVM_MMS=32m    #-XX:MaxMetaspaceSize default :320m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    networks:
      - nacos
    mem_limit: 1000m   # 最大使用内存

  art-mysql:
    image: mysql:8.0  # 镜像版本
    container_name: art-mysql8.0  # 容器名
    restart: unless-stopped    # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./mysql8.0/my.cnf:/etc/mysql/my.cnf"
      - "./mysql8.0/data:/var/lib/mysql"
      #      - "./mysql8.0/conf.d:/etc/mysql/conf.d"
      - "./mysql8.0/mysql-files:/var/lib/mysql-files"
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      #  TODO 设置root用户密码 此处默认为art-mysql-password
      MYSQL_ROOT_PASSWORD: art-mysql-password
    ports: # 映射端口
      - "3306:3306"

  art-redis:
    image: redis:6.0.8        # 镜像
    container_name: art-redis     # 容器名
    restart: unless-stopped        # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    #  TODO 设置用户密码 此处默认为art-redis-password
    command: redis-server /etc/redis/redis.conf --requirepass art-redis-password --appendonly no # 启动redis服务并添加密码 默认不开启redis-aof方式持久化配置
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./redis/data:/data"
      - "./redis/config/redis.conf:/etc/redis/redis.conf"  # `redis.conf`文件内容`http://download.redis.io/redis-stable/redis.conf`
    ports: # 映射端口
      - "6379:6379"