spring:
  application:
    name: fxz-demos
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
      username: nacos
      password: fxz-nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:fxz-application-common.yaml