spring:
  application:
    name: art-demo
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      username: nacos
      password: art-nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:art-common.yaml

art:
  hazelcast:
    port:
      - 5701
      - 5702
      - 5703
    members:
      - 127.0.0.1
