spring:
  application:
    name: fxz-demos
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:61.153.186.23}:8848
      discovery:
        server-addr: ${NACOS_HOST:61.153.186.23}:8848
      password: nacos
      username: nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:fxz-application-common.yaml