spring:
  application:
    name: fxz-z-laboratory
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:fxz-application-common.yaml
  data:
    mongodb:
      authentication-database: admin
      database: user
      username: admin
      password: "123456"
      host: fxz-mysql
      port: 27017