server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: fxz-register #服务名称
  security:
    user:
      name: fxz
      password: 123456
  boot:
    admin:
      client:
        url: http://${fxz-monitor-admin}:8401 #SBA服务端地址
        username: fxz #SBA服务端的用户名
        password: 123456 #SBA服务端的密码


eureka:
  instance:
    hostname: ${fxz-register} #Eureka服务端的地址
  client:
    register-with-eureka: false #是否将服务注册到Eureka服务端，由于我们这里是单节点的Eureka服务端，所以这里指定false
    fetch-registry: false #是否从Eureka服务端获取服务信息，因为这里是单节点的Eureka服务端，并不需要从别的Eureka服务端同步服务信息，所以这里设置为false
    instance-info-replication-interval-seconds: 30 #微服务更新实例信息的变化到Eureka服务端的间隔时间，单位为秒，这里指定为30秒
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/ #指定Eureka服务端的地址


info: #配置了SBA客户端的名称，描述和版本信息
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*' #将SBA客户端的所有监控端点都暴露给SBA服务端
  endpoint:
    health:
      show-details: ALWAYS #总是展示详细的健康信息