spring:
  application:
    name: fxz-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
