server:
  port: 8301
spring:
  application:
    name: fxz-gateway
  boot:
    admin:
      client:
        url: http://${fxz-monitor-admin}:8401
        username: fxz
        password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8001
    gateway:
      routes:
        - id: fxz-auth
          uri: lb://fxz-auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/fxz-auth
        - id: fxz-server-system
          uri: lb://fxz-server-system
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/fxz-server-system
        - id: fxz-server-test
          uri: lb://fxz-server-test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/fxz-server-test
      default-filters:
        - StripPrefix=1

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000


management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway